### PR TITLE
Jp 3

### PR DESCRIPTION
**Pull request by matozoid**

### CODE REVIEW

**Comment by matozoid** [comment]
Okay, this PR should be looked at carefully. I remember running through some of the obvious fixes, but the remaining problems were harder. The main issue is that I didn't have a thorough test set, so take all of this with a grain of salt. Feel free to open issues for questions on JP's issue tracker, or on the gitter channel.

**Comment by nightscape** [comment]
Hey @matozoid, thanks for the PR!
I'll try it out on my machine.
I'm not sure if the existing tests would discover problems, so probably I need to do manual inspection or improve the tests.

**Comment by matozoid** [comment]
To be clear: this is not at all finished or tested! I'm not sure you should thank me ;-)

**Comment by nightscape** [comment]
I had a look at it yesterday, but haven't yet managed to fix all compile errors...
If I stop making progress, what do you think about a pair programming session?

**Comment by matozoid** [comment]
Better come chat here: https://gitter.im/javaparser/javaparser - the whole team is there.

**Comment by er1c** [comment]
Replaced/included in https://github.com/scalagen/scalagen/pull/8

**Pull request closed without merging**
